### ISSUE TITLE
Problem with 2nd Generation

### ISSUE THREAD

**Issue by AhmadAkbari82** [user-none/sixaxispairer#3]
Unfortunately there are problems with the second Generation of Controller. I connected the Ps4 Controller to my laptop. It connected without any problems. So I re-entered my laptop MAC address with sixaxispair in Ps4 Controller. In fact, I just pressed the Update button. After that, the Ps4 Controller was no longer connected. I tried this with a few other devices. After changing the MAC address using SixAxisPairtool, the PS4 Controller does not connected anyway.
This problem is probably due to Generation. On the back of my gamepad is CUH-ZCT2E (or 4-597-175-01 serial number) which indicates the new version.
Does anyone have a solution?

**Comment by user-none** [comment]
The PS4 controller is not a Sixaxis; it is the original PS3. The PS4 is a Dual Shock 4 and works differently. This tool does not apply to that controller.
